name: Build and upload app

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and Test
      run: ./gradlew build test

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
