name: Build and upload app

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and Test
      run: ./gradlew build test

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Deploy To Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_DEV_APP_ID }}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: developer
        file: app/build/outputs/apk/release/app-release-unsigned.apk
